In [4]:
# different ways to respresent tensors

import tensorflow as tf
import numpy as np


m1 = [[1.0, 2.0], 
      [3.0, 4.0]]

m2 = np.array([[1.0 ,2.0],
             [3.0, 4.0]], dtype=np.float32)

m3 = tf.constant([[1.0, 2.0], [3.0, 4.0]])

2024-05-23 09:13:01.584087: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-23 09:13:01.674645: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-23 09:13:01.674791: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [8]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [9]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [10]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [11]:
# creating tensors

import tensorflow as tf

m1 = tf.constant([[1. , 2.]])

m2 = tf.constant([[1],
                 [2]])

m3 = tf.constant([[[1,2],
                  [3,4],
                  [5,6]],
                  [[7,8],
                   [9,10],
                   [11,12]]])

print(m1)
print(m2)
print(m3)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2), dtype=int32)


In [12]:
# using the negation operator

z = tf.constant([[1,2]])

negMatrix = tf.negative(z)

print(z)

tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [13]:
negMatrix

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[-1, -2]], dtype=int32)>

## useful tf funcs

tf.add(x, y)—Adds two tensors of the same type, x + y

tf.subtract(x, y)—Subtracts tensors of the same type, x – y

tf.multiply(x, y)—Multiplies two tensors elementwise

tf.pow(x, y)—Takes the elementwise x to the power of y

tf.exp(x)—Equivalent to pow(e, x), where e is Euler’s number (2.718 …)

tf.sqrt(x)—Equivalent to pow(x, 0.5)

tf.div(x, y)—Takes the elementwise division of x and y

tf.truediv(x, y)—Same as tf.div, but casts the arguments as a float

tf.floordiv(x, y)—Same as truediv, but rounds down the final answer into an integer

tf.mod(x, y)—Takes the elementwise remainder from division

In [2]:
# using variable
import tensorflow as tf

raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]
spike = tf.Variable(False)

for i in range(1, len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5:
        spike.assign(True)
    else:
        spike.assign(False)
    print('spike: ', spike.numpy())

spike:  False
spike:  True
spike:  False
spike:  False
spike:  True
spike:  False
spike:  True


In [6]:
tf.__version__

'2.13.0'

In [14]:
raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]

spikes = tf.Variable([False]*len(raw_data), name='spikes')

for i in range(1, len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5:
        spikes[i].assign(True)

for i in range(len(raw_data)):
    print(spikes[i].numpy())
    
checkpoint = tf.train.Checkpoint(spikes=spikes)
save_path = checkpoint.save('./checkpoints/spikes.ckpt')
print('checkpoint file path is: ', save_path)

False
False
True
False
False
True
False
True
checkpoint file path is:  ./checkpoints/spikes.ckpt-1


In [15]:
restored_spikes = tf.Variable([False] * len(raw_data))
checkpoint = tf.train.Checkpoint(spikes=restored_spikes)
checkpoint.restore(tf.train.latest_checkpoint('./checkpoints')).expect_partial()

In [16]:
restored_spikes

<tf.Variable 'Variable:0' shape=(8,) dtype=bool, numpy=array([False, False,  True, False, False,  True, False,  True])>

In [18]:
# reduce sum function

import tensorflow as tf

img = tf.random.normal([2,3,4])

print(img)

tf.Tensor(
[[[ 0.14988168 -0.2865736   0.996201   -0.19231685]
  [ 1.0491823   0.1621614   0.7639901  -0.08952646]
  [-2.0867417   0.49705365  0.3903      0.18710676]]

 [[ 0.4658837   0.7195598   1.5447904   1.611349  ]
  [-0.4753937   0.3851614  -0.17793776  0.19236968]
  [-0.5651991  -0.565183    2.6565568  -0.82590586]]], shape=(2, 3, 4), dtype=float32)


In [20]:
total_sum = tf.reduce_sum(img)

print(total_sum)

tf.Tensor(6.50677, shape=(), dtype=float32)


In [21]:
total_sum = tf.reduce_sum(img, axis=0)

print(total_sum)

tf.Tensor(
[[ 0.6157654   0.4329862   2.5409913   1.4190321 ]
 [ 0.5737886   0.5473228   0.58605236  0.10284323]
 [-2.6519408  -0.06812933  3.0468569  -0.6387991 ]], shape=(3, 4), dtype=float32)


In [22]:
total_sum = tf.reduce_sum(img, axis=1)

print(total_sum)

tf.Tensor(
[[-0.88767767  0.37264144  2.150491   -0.09473655]
 [-0.57470906  0.5395382   4.0234094   0.9778128 ]], shape=(2, 4), dtype=float32)


In [23]:
total_sum = tf.reduce_sum(img, axis=2)

print(total_sum)

tf.Tensor(
[[ 0.6671922   1.8858073  -1.0122813 ]
 [ 4.341583   -0.07580037  0.7002689 ]], shape=(2, 3), dtype=float32)


In [33]:
import numpy as np
import tensorflow as tf

# Generate raw_data with normal distribution
raw_data = np.random.normal(10, 1, 100)

# Define constants and variables
alpha = tf.constant(0.05, dtype=tf.float32)
prev_avg = tf.Variable(0.0, dtype=tf.float32)

log_dir = './logs'

summary_writter = tf.summary.create_file_writer(log_dir)

@tf.function
def update_running_average(curr_val, prev_avg, alpha):
    ret = alpha * curr_value + (1 - alpha) * prev_avg
    return ret

In [34]:
prev_avg.assign(0.0)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=0.0>

In [35]:
for i, val in enumerate(raw_data):
    curr_value = tf.constant(val, dtype=tf.float32)
    new_avg = update_running_average(val, prev_avg, alpha)
    prev_avg.assign(new_avg)
    
    with summary_writter.as_default():
        tf.summary.scalar("running_average", new_avg, step=i)
        tf.summary.scalar("incoming_values", val, step=i)
        
    print(val, new_avg.numpy())

10.81005611886239 0.5405028
8.77616028121942 1.0539804
10.293554635002081 1.541784
10.888314118830243 2.0051975
10.153312442409858 2.4454403
8.70264671221735 2.863671
9.096249449269935 3.2609904
9.421621680247098 3.6384437
10.277977287677489 3.9970243
8.785608083902916 4.337676
10.337824191161474 4.661295
9.404467320961995 4.968733
10.291243614784493 5.2607985
11.328256799549928 5.5382614
9.656731208453778 5.8018513
11.925894424669648 6.0522614
11.47524610847533 6.2901506
9.08872836616721 6.5161457
8.177676018269548 6.7308407
9.848412901179971 6.934801
10.243021266835454 7.128564
10.54361333887367 7.3126383
7.494128422346517 7.487509
9.164784958194112 7.653636
10.706796676813623 7.8114567
9.969988314482876 7.9613867
9.296543157105212 8.10382
9.227668149568556 8.239132
9.09425788613281 8.367678
10.251836670853038 8.489797
10.788440527785513 8.605809
10.966529239617216 8.716022
9.664240133137794 8.820723
10.687147592858656 8.920189
9.794122715748522 9.014682
8.974492543112525 9.10445
9.4

In [36]:
print("Final running average:", prev_avg.numpy())

Final running average: 10.746049
